# https://www.appveyor.com/docs/appveyor-yml

environment:
  global:
    THRESHOLD: "20"
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "12"
    - nodejs_version: "10"

clone_depth: 10

version: "{build}"
build: off
deploy: off

branches:
    only:
      - master

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@latest
  - node --version
  - npm --version
  - npm ci

cache:
  - node_modules

test_script:
  - npm run test-only
